language: php
php:
  - 7.1
  - 7.2
before_install:
  - openssl aes-256-cbc -K $encrypted_2b7e0505597a_key -iv $encrypted_2b7e0505597a_iv -in .travis/deploy_rsa_encrypted -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install: composer install --no-interaction --prefer-source
script:
  - vendor/bin/phpunit