language: php
php:
  - 7.0
  - 7.1
  - 7.2
env:
  matrix:
    - COMPOSER_PREF="--prefer-lowest"
    - COMPOSER_PREF=""
before_install:
  - ssh-keygen -N "" -f ~/.ssh/id_rsa
    #  - openssl aes-256-cbc -K $encrypted_2b7e0505597a_key -iv $encrypted_2b7e0505597a_iv -in .travis/deploy_rsa_encrypted -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install: composer update --no-interaction --prefer-source $COMPOSER_PREF
script:
  - vendor/bin/phpunit
